version: '3'
services:
  app:
    build: .
    user: '1000:1000'
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - ./src:/src
    stdin_open: true
    tty: true
    command: sh -c "cd ./frontend && npm install && npm run serve"
